use std::path::Path;
use std::process::Command;

use super::suffix_path;

pub fn to_images(input: &Path, format: &str, dpi: u32) -> Result<Vec<String>, String> {
    let output_dir = input.parent().unwrap_or_else(|| Path::new("."));
    let stem = input
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("output");
    let dpi_str = dpi.to_string();
    let output_prefix = output_dir.join(stem);

    let cmd_result = match format {
        "jpeg" | "jpg" => Command::new("pdftoppm")
            .args([
                "-jpeg",
                "-r",
                &dpi_str,
                input.to_str().unwrap(),
                output_prefix.to_str().unwrap(),
            ])
            .output(),
        "png" => Command::new("pdftoppm")
            .args([
                "-png",
                "-r",
                &dpi_str,
                input.to_str().unwrap(),
                output_prefix.to_str().unwrap(),
            ])
            .output(),
        "tiff" | "tif" => Command::new("pdftoppm")
            .args([
                "-tiff",
                "-r",
                &dpi_str,
                input.to_str().unwrap(),
                output_prefix.to_str().unwrap(),
            ])
            .output(),
        "ppm" => Command::new("pdftoppm")
            .args([
                "-r",
                &dpi_str,
                input.to_str().unwrap(),
                output_prefix.to_str().unwrap(),
            ])
            .output(),
        _ => return Err(format!("Unsupported image format: {format}")),
    };

    match cmd_result {
        Ok(output) if output.status.success() => {
            let ext_match = match format {
                "jpeg" | "jpg" => "jpg",
                other => other,
            };
            let mut generated_files = Vec::new();
            if let Ok(entries) = std::fs::read_dir(output_dir) {
                for entry in entries.flatten() {
                    let path = entry.path();
                    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                        if name.starts_with(stem) && name != input.file_name().unwrap().to_str().unwrap() {
                            // Match files generated by pdftoppm (stem-N.ext pattern)
                            if name.ends_with(ext_match)
                                || (format == "jpeg" && name.ends_with("jpg"))
                            {
                                generated_files.push(path.to_string_lossy().to_string());
                            }
                        }
                    }
                }
            }

            if generated_files.is_empty() {
                Err("No output files were generated".to_string())
            } else {
                generated_files.sort();
                Ok(generated_files)
            }
        }
        Ok(output) => {
            let stderr = String::from_utf8_lossy(&output.stderr);
            Err(format!("pdftoppm failed: {stderr}"))
        }
        Err(e) => Err(format!(
            "Failed to run pdftoppm (is poppler installed? brew install poppler): {e}"
        )),
    }
}

pub fn to_svg(input: &Path) -> Result<Vec<String>, String> {
    let output = suffix_path(input, "", Some("svg"));

    let cmd_result = Command::new("pdftocairo")
        .args([
            "-svg",
            input.to_str().unwrap(),
            output.to_str().unwrap(),
        ])
        .output();

    match cmd_result {
        Ok(out) if out.status.success() => Ok(vec![output.to_string_lossy().to_string()]),
        Ok(out) => {
            let stderr = String::from_utf8_lossy(&out.stderr);
            Err(format!("pdftocairo failed: {stderr}"))
        }
        Err(e) => Err(format!(
            "Failed to run pdftocairo (is poppler installed? brew install poppler): {e}"
        )),
    }
}
